BASE_TASK_CONFIG_PATH: "configs/audionav/dav_nav/replica/audiogoal.yaml"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
TEST_EPISODE_COUNT: 500
VIDEO_OPTION: []
VISUALIZATION_OPTION: []
#ENCODE_DEPTH: False
USE_SYNC_VECENV: True


EVAL:
  SPLIT: "val_multiple_unheard"
  USE_CKPT_CONFIG: True