BASE_TASK_CONFIG_PATH: "configs/audionav/dav_nav/replica/audiogoal_dynamic_source_val_test.yaml"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
TEST_EPISODE_COUNT: 1000
#VIDEO_OPTION: ["tensorboard"]
VIDEO_OPTION: []
VISUALIZATION_OPTION: []
#ENCODE_DEPTH: False
USE_SYNC_VECENV: False


EVAL:
  SPLIT: "test_multiple"
  USE_CKPT_CONFIG: True