BASE_TASK_CONFIG_PATH: "configs/audionav/dav_nav/mp3d/audiogoal_complex_scenarios_dynamic_source_val.yaml"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
TEST_EPISODE_COUNT: 500
VIDEO_OPTION: []
VISUALIZATION_OPTION: []
ENCODE_DEPTH: True
USE_SYNC_VECENV: True

EVAL:
  SPLIT: "val_multiple_unheard"
  USE_CKPT_CONFIG: True