ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128


#    NOISE_MODEL: RedwoodDepthNoiseModel

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "mp3d"
  GRID_SIZE: 1.0
  AUDIO:
    RIR_SAMPLING_RATE: 16000
    trainWithSecondAudio: True
    trainWithSpecAugment: True
    trainWithDistractor: True
    moving_source: True
    time_mask_param: 12

TASK:
  TYPE: AudioNav

  SENSORS: ['SPECTROGRAM_SENSOR', 'EGOMAP_SENSOR', 'POINTGOAL_WITH_GPS_COMPASS_SENSOR', "GEOMETRIC_MAP", "ACTION_MAP", 'COLLISION', 'ACOUSTIC_MAP', 'INTENSITY', 'AUDIOGOAL_SENSOR']
  GOAL_SENSOR_UUID: spectrogram
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "CARTESIAN"
    DIMENSIONALITY: 2

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'NUM_ACTION', 'DYNAMIC_SUCCESS_WEIGHTED_BY_PATH_LENGTH', 'DYNAMIC_SUCCESS_WEIGHTED_BY_NUM_ACTION']
  SPL:
    TYPE: SPL
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 10000
    DRAW_BORDER: True
    DRAW_SHORTEST_PATH: True
  DISTANCE_TO_GOAL:
    DISTANCE_TO: POINT

  GEOMETRIC_MAP:
    MAP_SIZE: 200
    INTERNAL_MAP_SIZE: 1200
    MAP_RESOLUTION: 0.1
  ACOUSTIC_MAP:
    MAP_SIZE: 20
    MAP_RESOLUTION: 1.0
  ACTION_MAP:
    MAP_SIZE: 3
    MAP_RESOLUTION: 1.0

DATASET:
  TYPE: "AudioNav"
  SPLIT: "train_multiple"
  CONTENT_SCENES: ["*"]
  VERSION: 'v1'
  SCENES_DIR: "data/scene_datasets/mp3d"
  DATA_PATH: "data/datasets/audionav/mp3d/{version}/{split}/{split}.json.gz"
