BASE_TASK_CONFIG_PATH: "configs/audionav/dav_nav/mp3d/audiogoal_telephone_complex_scenarios.yaml"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
TEST_EPISODE_COUNT: 500
VIDEO_OPTION: []
VISUALIZATION_OPTION: []
ENCODE_DEPTH: True
USE_SYNC_VECENV: True


EVAL:
  SPLIT: "val_telephone"
  USE_CKPT_CONFIG: True